apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /logs/pythonapp.log/pythonapp.log
      fields:
        app: pythonapp

    output.elasticsearch:
      hosts: ["107.20.71.149:9200"]
