apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: arieldomchik/ariel:pythonapp-new
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /pythonapp.log
              name: logs-volume
            - name: pythonapp-volume
              mountPath: /instance/crud.db

      volumes:
        - name: pythonapp-volume
          persistentVolumeClaim:
            claimName: pythonapp-pvc
        - name: logs-volume
          hostPath:
            path: /pythonapp.log
