apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: arieldomchik/ariel:pythonapp
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /crud.db
              name: db-volume
            - mountPath: /logs/pythonapp.log
              name: logs-volume
      volumes:
        - name: db-volume
          hostPath:
            path: /crud.db
        - name: logs-volume
          hostPath:
            path: /pythonapp.log
