apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      nodeSelector:
        vol: pers
      containers:
        - name: pythonapp
          image: arieldomchik/ariel:pythonapp-v2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: pythonapp-volume
              mountPath: /logs
              subPath: pythonapp.log
            - name: pythonapp-volume
              mountPath: /instance
              subPath: crud.db
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.12.1
          volumeMounts:
            - name: pythonapp-volume
              mountPath: /logs
              readOnly: true
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch-cluster
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: changeme
            - name: ELASTICSEARCH_INDEX
              value: pythonapp
          args: [
            "-e", 
            "-c", "/usr/share/filebeat/filebeat.yml"
          ]
      volumes:
        - name: pythonapp-volume
          persistentVolumeClaim:
            claimName: pythonapp-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-config
