apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: arieldomchik/ariel:pythonapp
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /efs/crud.db
              name: volume
      volumes:
        - name: volume
          hostPath:
            path: /efs/crud.db
      volumes:
        - name: logs
          hostPath:
            path: /pythonapp.log
