apiVersion: v1
kind: PersistentVolume
metadata:
  name: pythonapp-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0f31a590eac92556c
    fsType: ext4
  storageClassName: pythonapp-storageclass
