apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pythonapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: pythonapp-storageclass
