apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pythonapp-storageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate
